### ISSUE TITLE
Failed to convert islands on paper/spigot 1.19.1

### ISSUE THREAD

**Issue by Johandrex** [BentoBoxWorld/a2b#24]
**Description**
Getting the following error down below for all player files, no islands are converted
`[BentoBox] [BSkyBlock] Error trying to import player file 096d9d33-74ce-4bfa-a0ee-4f98bae2e776.yml: Cannot invoke "org.bukkit.Location.getWorld()" because "center" is null`

Happens when attempting to convert from ASkyblock 3.0.6.11 to BentoBox 1.20.1 on PaperMC 1.19.1 with the command "bsb convert".

Following addons were used when converting: BSkyblock 1.15.2, Challenges 0.8.4, Level 2.9.0, Warps 1.12.0, Converter 1.8.2

(PS: could not use Challenges 1.0.0 with the current converter addon, results in the following error Caused by: java.lang.NoSuchMethodError: 'world.bentobox.challenges.ChallengesManager world.bentobox.challenges.ChallengesAddon.getChallengesManager()')

**Steps to reproduce the behavior:**
1. Upgrade to earlier mentioned addons from ASkyblock using the following guide at https://docs.bentobox.world/en/latest/Converter/
**Server Information:**

[Please complete the following information:]
 - Database being used (Flat file, MySQL, Mongo): Flatfile
 - OS: Ubuntu 20.04
 - Java Version: Java 17
 - BentoBox version: 1.20.1

```
[18:42:22 INFO]: Running PAPER Invalid.
[18:42:22 INFO]: BentoBox version: 1.20.1
[18:42:22 INFO]: Database: JSON
[18:42:22 INFO]: Loaded Game Worlds:
[18:42:22 INFO]: skyworld (BSkyBlock): Overworld, Nether, The End
[18:42:22 INFO]: Loaded Addons:
[18:42:22 INFO]: BSkyBlock 1.15.2 (ENABLED)
[18:42:22 INFO]: Challenges 0.8.4 (ENABLED)
[18:42:22 INFO]: Level 2.9.0 (ENABLED)
[18:42:22 INFO]: Warps 1.12.0 (ENABLED)

```

**Comment by Johandrex** [comment]
Getting the following errors for all players/islands when trying to convert with the latest dev build
```

java.lang.NullPointerException: Cannot invoke "org.bukkit.Location.getWorld()" because "center" is null
[05:47:46 WARN]:        at BentoBox.jar//world.bentobox.bentobox.database.objects.Island.setCenter(Island.java:823)
[05:47:46 WARN]:        at world.bentobox.a2b.commands.AdminConvertCommand.processIsland(AdminConvertCommand.java:361)
[05:47:46 WARN]:        at world.bentobox.a2b.commands.AdminConvertCommand.convertplayers(AdminConvertCommand.java:302)
[05:47:46 WARN]:        at world.bentobox.a2b.commands.AdminConvertCommand.execute(AdminConvertCommand.java:130)
[05:47:46 WARN]:        at BentoBox.jar//world.bentobox.bentobox.api.commands.CompositeCommand.call(CompositeCommand.java:273)
[05:47:46 WARN]:        at BentoBox.jar//world.bentobox.bentobox.api.commands.CompositeCommand.execute(CompositeCommand.java:246)
[05:47:46 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155)
[05:47:46 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909)
[05:47:46 WARN]:        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:872)
[05:47:46 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:473)
[05:47:46 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:447)
[05:47:46 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1415)
[05:47:46 WARN]:        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1191)
[05:47:46 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[05:47:46 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Johandrex** [comment]
My fault, I didn't rename the world from "bskyblock" to "skyworld" in the BSkyblock configuration file before using the "bsb convert" command. It works perfectly now!
